l_korean:
 PRODUCTION_PRODUCTION_LABEL: "생산"
 PRODUCTION_EQUIPMENTPOOL_LABEL: "비축"
 PRODUCTION_EFFICIENCY_LABEL: "§T효율§!"
 PRODUCTION_EQUIPMENT_LABEL: "장비"
 PRODUCTION_ADJUSTERS_LABEL: "조정치"
 PRODUCTION_MATERIALS_LABEL: "원료"
 PRODUCTION_FACTORIES_LABEL: "공장"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL: "군수공장"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL: "해군 조선소"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL: "민간공장"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL_SHORT: "조선소"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL: "가용 군수공장"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL: "가용 해군 조선소"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL: "가용 민간공장"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE: "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL: "§T육군 & 공군 장비§!"
 PRODUCTION_NAVAL_LABEL: "§T해군 장비§!"
 PRODUCTION_BUILDINGS_LABEL: "§T건물 건설§!"
 PRODUCTION_PRODUCING_DAILY: "매일 $AMOUNT$ 생산"
 PRODUCTION_PRODUCING_WEEKLY: "매주 $AMOUNT$ 생산"
 PRODUCTION_PRODUCING_MONTHLY: "매달 $AMOUNT$ 생산"
 PRODUCTION_PRODUCING_YEARLY: "매년 $AMOUNT$ 생산"
 PRODUCTION_PRODUCING_ETA_DATE: "다음 완성: $DATE$"
 PRODUCTION_REPAIRING_ETA_DATE: "수리 완료: $DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS: "$AMOUNT$일 뒤"
 PRODUCTION_PRODUCING_ETA_WEEKS: "$AMOUNT$주 뒤"
 PRODUCTION_PRODUCING_ETA_MONTHS: "$AMOUNT$개월 뒤"
 PRODUCTION_PRODUCING_ETA_YEARS: "$AMOUNT$년 뒤"
 PRODUCTION_PRODUCING_NEVER: "§R불가§!"
 PRODUCTION_REPAIRING_PAUSED_NAVAL_TRANSFER: "해당 부대가 해상 이동 중이므로 수리가 일시적으로 중지되었습니다."
 PRODUCTION_PRODUCING_NO_FACTORIES: "§R할당된 공장 없음§!"
 PRODUCTION_PRODUCING_NONE: "§R생산량 없음§!"
 PRODUCTION_CAN_NOT_DEPLOY: "§R배치 불가능§!"
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER: "인력 부족"
 PRODUCTION_CAN_NOT_DEPLOY_NO_CAPITAL: "자금 접근 불가"
 PRODUCTION_INCREASE_PRIORITY_LABEL: "우선순위를 높이려면 §G클릭하십시오§H§!.\nShift + 클릭하면 해당 생산에 §H최우선 순위§!를 부여합니다.§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL: "우선순위를 낮추려면 §G클릭하십시오§H§!.\nShift + 클릭하면 해당 생산에 §H최하위 우선순위§!를 부여합니다.§!"
 PRODUCTION_PRIORITY_DELAYED: "우선순위가 높은 생산 라인은 우선순위가 낮은 생산 라인보다 먼저 자원을 할당 받습니다."
 PRODUCTION_EFFICIENCY: "£prod_eff  §T생산 효율: $AMOUNT|H2%$§!"
 PRODUCTION_EFFICIENCY_MOD: "£prod_eff §T생산 효율: $AMOUNT|Y2%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN: "£prod_eff  §T생산 효율: $AMOUNT|H2%$§! (매일 $GAIN|H3%$)"
 PRODUCTION_EFFICIENCY_DESC: "§T평균 공장 생산 효율입니다.\n생산 효율은 생산한 유닛마다 $VALUE|H=2$% 증가하며, 가동 중인 공장에 균등하게 분배됩니다.§!"
 PRODUCTION_RESOURCE_PENALTY: "§T자원 부족: $AMOUNT|R2%$§!"
 PRODUCTION_RESOURCE_PENALTY_WITH_MIO: "§T자원 부족: $AMOUNT|R2%$§! ($FROM_MIO$)"
 PRODUCTION_ASSIGN_EQUIPMENT: "§T생산을 시작하려면 장비를 배치하십시오.§!"
 PRODUCTION_MATERIALS_OIL: "석유"
 PRODUCTION_MATERIALS_ALUMINIUM: "알루미늄"
 PRODUCTION_MATERIALS_RUBBER: "고무"
 PRODUCTION_MATERIALS_CHROMIUM: "크롬"
 PRODUCTION_MATERIALS_STEEL: "강철"
 PRODUCTION_MATERIALS_TUNGSTEN: "텅스텐"
 PRODUCTION_MATERIALS_COAL: "석탄"
 PRODUCTION_MATERIAL_VAL: "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON: "기갑 차량 제작"
 PRODUCTION_VEHICLES_BUTTON_DISABLED: "기갑 차량이 §R발명되지 않았습니다§!!"
 PRODUCTION_VEHICLES_BUTTON_NO_FACTORIES_DISABLED: "우리에게는 §R군수공장이 없습니다!§!"
 PRODUCTION_INFANTRY_BUTTON: "보병 및 포병 장비 제작"
 PRODUCTION_INFANTRY_BUTTON_DISABLED: "보병 및 포병 장비가 §R발명되지 않았습니다§!!"
 PRODUCTION_INFANTRY_BUTTON_NO_FACTORIES_DISABLED: "우리에게는 §R군수공장이 없습니다!§!"
 PRODUCTION_AIRCRAFT_BUTTON: "항공기 제작"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED: "항공기가 §R발명되지 않았습니다§!!"
 PRODUCTION_AIRCRAFT_BUTTON_NO_FACTORIES_DISABLED: "우리에게는 §R군수공장이 없습니다§!!"
 PRODUCTION_SHIPS_BUTTON: "함선 건조"
 PRODUCTION_SHIPS_BUTTON_DISABLED: "함선이 §R발명되지 않았습니다§!!"
 PRODUCTION_SHIPS_BUTTON_NO_DEPLOY_DISABLED: "우리에게는 §R항구가 없습니다§!!"
 PRODUCTION_SHIPS_BUTTON_NO_FACTORIES_DISABLED: "우리에게는 §R조선소가 없습니다§!!"
 PRODUCTION_CONSUMER_GOODS_VALUE: "$VALUE$"
 PRODUCTION_CONSUMER_GOODS: "소비재"
 PRODUCTION_CONSUMER_GOODS_LABEL: "§H소비재§!"
 PRODUCTION_CONSUMER_GOODS_DESC: "현재 우리의 경제 정책으로 볼 때, 국민은 우리 민간 및 군수공장 $TOTAL_FACTORIES|H$개 중 $PERCENTAGE|H0%$는 소비재를 생산할 것이라 기대합니다. 이 수요는 $GENERAL_FACTORIES|H$개의 민간공장을 통해 충당되며, 남아 있는 $OPERATIONAL|H$개의 공장 중 $TRADE_USABLE|H$개를 무역에 이용할 수 있습니다."
 PRODUCTION_CIV_AND_MIL_FACTORIES: "민간 및 군수공장: $KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES: "필요한 소비재 공장: $KEY|H$"
 PRODUCTION_CONSUMER_GOODS_FACTORIES_BASE_EXPECTATION: "기본 기대치:"
 PRODUCTION_CONSUMER_GOODS_FACTORIES_FACTOR: "요인:"
 PRODUCTION_CONSUMER_GOODS_FACTORIES_FACTORS_MULTIPLIED: "배수 요인 합계: $PERCENTAGE|H0%$"
 PRODUCTION_MATERIAL_COST_DESC: "§T이 생산 라인은 $MATERIAL|H$(을)를 $AMOUNT|0H$ 소비하고 있습니다.§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC: "§T최대 효율로 생산하기 위해서는 $AMOUNT|0H$(이)가 더 필요합니다.§!\n생산은 계속되지만, 속도가 §R감소합니다§!."
 PRODUCTION_LINE_CANCEL: "§G클릭§!하여 해당 생산 라인 §R취소.§!\n§GShift + 클릭§!하여 모든 생산 라인 §R취소§!."
 PRODUCTION_LINE_CANCEL_SHIP_REFIT: "개장 중인 이 함선을 §R침몰§!시키려면 §G클릭§!하십시오."
 PRODUCTION_CREATE_VARIANT: "§H파생형 제작§!"
 PRODUCTION_CANCEL_CONSTRUCTION: "§T이 건설 취소.§!"
 PRODUCTION_VARIANT_OBSOLETE_YES: "재취역"
 PRODUCTION_VARIANT_OBSOLETE_NO: "퇴역"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC: "§G클릭§!하여 이 파생형을 재취역시키고, 최신 장비로 간주합니다."
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC: "§G클릭§!하여 이 파생형을 오래된 구식 장비로 취급하여 퇴역시킵니다."
 TRADE_FACTORIES_VALUE: "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE: "생산 라인 취소"
 CONFIRMCANCELPRODUCTIONLINE_DESC: "정말 이 생산 라인을 §R취소§!하시겠습니까?"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE: "모든 생산 라인 취소"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC: "정말 모든 생산 라인을 §R취소§!하시겠습니까?"
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE: "장비 교체"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC: "정말로 장비를 §R교체§!하시겠습니까? $DAYS|R$일 동안의 생산이 손실됩니다."
 CONFIRMCANCELCONSTRUCTION_TITLE: "건설 취소"
 CONFIRMCANCELCONSTRUCTION_DESC: "정말로 $REGION|H$의 $CONSTRUCTION|H$ 건설을 §R취소§!하시겠습니까?"
 CONFIRMCANCELCONSTRUCTION_RAILWAY_DESC: "정말로 $NAME|H$ 철도 건설을 §R취소§!하시겠습니까?"
 CONFIRMCANCELCONSTRUCTIONS_TITLE: "건설 취소"
 CONFIRMCANCELCONSTRUCTIONS_DESC: "정말로 모든 건설을 §R취소§!하시겠습니까?"
 INFINITY: "£infinity_icon!"
 PRODUCTION_EQUIPMENT_NEED: "수요: $AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE: "항구에 배치: $BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET: "태스크 포스 배치: $FLEET|H$"
 PRODUCTION_DEPLOY_TO_RESERVE_FLEET_THEATER: "전구 예비대에 배치: $THEATER|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE: "배치 대상인 $FLEET|H$(은)는 기지가 없음."
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET: "$STATE|H$의 기지에 위치한 $FLEET|H$에 태스크 포스를 배치합니다."
 PRODUCTION_NAVAL_DEPLOYMENT_THEATER: "$STATE|H$의 기지에 위치한 $THEATER|H$ 전역에 배치합니다."
 PRODUCTION_NAVAL_DEPLOYMENT_BASE: "배치 대상 기지는 $STATE|H$에 있음."
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE: "배치 대상이 설정되지 않음."
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE: "배치할 수 없음"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT: "자동"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING: "폐기 중"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC: "배치할 기지가 없습니다. 함선은 완성되는 즉시 폐기될 것입니다."
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING: "비축"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM: "§G우클릭해서 해당 지역으로 이동§!"
 PRODUCTION_NAVAL_DEPLOY_LIST: "배치 대상"
 WEEKLY_PRODUCTION: "매주 생산"
 PRODUCTION_WORKING_FACTORIES: "현재 생산 라인 중 하나에서 작업 중인 공장의 수입니다."
 PRODUCTION_WORKING_DOCKYARDS: "현재 생산 라인 중 하나에서 작업 중인 조선소의 수입니다."
 PRODUCTION_WORKING_DOCKYARDS_FOR_REPAIRS: "현재 함선 수리용으로 사용 중인 조선소의 수입니다."
 PRODICTION_MIC_TRANSFERED: "우리 공장 중 $AMOUNT|Y$개는 $OVERLORD|Y$ 측이 사용합니다."
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT: "우리의 종속국으로부터 군수공장 $AMOUNT|Y$개를 받고 있습니다."
 PRODICTION_MIC_SENT_TO_OVERLORD: "우리 군수공장 중 $AMOUNT|R$개는 종주국에 주어지고, $LEFT|H$개만 남았습니다."
 PRODICTION_MIC_RECEIVED_FROM_EXILE_DONATIONS: "우리 군수공장 중 $AMOUNT|Y$(은)는 우리가 받아들인 망명정부에서 기부받은 것입니다."
 PRODUCTION_MAX_EFFICIENCY_BASE: "기본 한도: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT: "£prod_eff_cap  생산 효율 한도: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT: "£prod_eff_cap  생산 효율 한도는 £prod_eff 생산 효율의 최대치를 결정합니다. 한도는 £tech_mod 기술로 증가시킬 수 있습니다."
 PRODUCTION_RESOURCES_PER_FACTORY: "§H공장당 자원 사용:§!"
 PRODUCTION_RESOURCE_COST: "$VALUE$"
 PRODUCTION_MATERIAL_NO_WASTE: "생산 라인이 해당 자원을 낭비하고 있지 않습니다."
 PRODUCTION_MATERIAL_WASTE: "생산 라인이 해당 자원을 $WASTE|R2$만큼 낭비하고 있습니다."
 PRODUCTION_SPEED: "생산 속도: $SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS: "§Y생산량 변동치:§!"
 INDUSTRIAL_CAPACITY_FACTOR: "공장 생산량: $VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS: "공장 생산량 변동치:"
 INDUSTRIAL_PROGRESS: "$BUILDING|H$(은)는 $PROGRESS|0H$/$COST|0H$ ( $VALUE|0%H$ ) 완료되었습니다."
 INDUSTRIAL_PROGRESS_REPAIR: "$BUILDING|H$의 수리 진행도: $PROGRESS|%1H$"
 INDUSTRIAL_BASE_FACTORY_OUTPUT: "기본 공장 생산량: $VALUE|H$"
 INDUSTRIAL_BASE_SPEED: "$FACTORIES|0H$개의 공장을 통한 생산량: $VALUE|H$"
 PROD_COST_VALUE: "£production_cost  $VALUE$"
 NAVPROD_COST_VALUE: "£navprod_cost  $VALUE$"
 PRODUCTION_CIVILIAN_FACTORIES_HEADER: "§H사용 중인 공장§!"
 PRODUCTION_CIVILIAN_FACTORIES_TOTAL: "총합: $VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE: "미사용: $VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY: "사용 중: $VALUE|R$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED: "보유량: $VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_TRADE: "무역 수출: §G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_LICENSES: "면허 수출: §G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_SUBJECTS: "종속국으로부터: §G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OTHERS: "타국으로부터: §G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OCCUPATION: "점령지로부터: §G+$VAL$§!"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_MASTER: "종주국에 상납: $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_OTHERS: "다른 나라에 상납: $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_TRADE: "무역 수입: $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_LICENSES: "면허 수입: $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_DAMAGED: "손상됨: $VAL|R$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED: "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED: "$AMOUNT|0G$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE: "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE: "일일 손익: $VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION: "현재 일일 손익에 따르면 우리의 수요는 $VALUE|0Y$일 후에 §Y충족§!됩니다."
 PRODUCTION_EQUIPMENT_FILLED: "현재로서는 수요가 §G충족§!된 상태입니다."
 PRODUCTION_EQUIPMENT_LOSSES: "우리는 어제 $VALUE|R$ 장비를 잃었습니다."
 PROD_LINE_PLANE_DEST_RESERVES_DUE_TO_MANPOWER: "§Y증원§! 요청에 응할 만큼의 §H인력§!을 가지고 있지 못해 §Y예비대§!로 이동합니다."
 PROD_LINE_PLANE_DEST_RESERVES: "§Y예비대§!로 이동됨"
 PROD_LINE_PLANE_DEST_UPGRADING: "§Y개선§!에 필요함"
 PROD_LINE_PLANE_DEST_REINFORCEMENT: "§Y증원§!에 필요함"
 PROD_LINE_LAND_DEST_RESERVES: "§Y비축§! 중"
 PROD_LINE_LAND_DEST_UPGRADING: "§Y개선§!에 필요함"
 PROD_LINE_LAND_DEST_REINFORCEMENT: "§Y증원§!에 필요함"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE: "건물 철거"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC: "정말로 이 건물을 §R철거§!하시겠습니까?"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE: "건설 취소"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC: "정말로 이 건설을 §R취소§!하시겠습니까?"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE: "건물 전환 취소"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC: "정말로 이 건물 전환을 §R취소§!하시겠습니까?"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE: "건물 전환"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC: "정말로 이 건물을 §R전환§!하시겠습니까?"
 PRODUCTION_EFFICIENCY_GAIN_BASE: "매일 기본 획득량: $VAL|H3%$"
 PRODUCTION_RESOURCE_FACTOR: "자원 부족: $VAL|%+$"
 PRODUCTION_RESOURCE_FACTOR_WITH_MIO: "자원 부족: $VAL|%+$ ($FROM_MIO$)"
 PRODUCTION_OUTPUT_EXPLAIN: "우리의 $FACTORIES|Y$ £factory_item 군수공장은 £production_cost $OUTPUT|Y$의 생산력을 가지고 있습니다.\n$ITEM|Y$의 비용은 $ITEM_COST|2Y$ £production_cost이므로, $PERTIMEPERIOD$만큼 생산할 수 있습니다.\n"
 PRODUCTION_OUTPUT_EXPLAIN_REFIT: "우리의 $FACTORIES|Y$ £factory_item 군수공장은 £production_cost $OUTPUT|Y$의 생산력을 가지고 있습니다.\n$FROM|Y$ 전환의 비용은 $COST|2Y$ £production_cost이므로, $PERTIMEPERIOD$만큼 전환할 수 있습니다.\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL: "우리의 $FACTORIES|Y$ £naval_factory_icon 해군 조선소는 £navprod_cost $OUTPUT|Y$의 생산력을 가지고 있습니다.\n$ITEM|Y$의 비용은 $ITEM_COST|2Y$ £navprod_cost 이므로, $PERTIMEPERIOD$만큼 생산할 수 있습니다.\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL_REFIT: "우리의 $FACTORIES|Y$ £naval_factory_icon 해군 조선소는 £navprod_cost $OUTPUT|Y$의 생산력을 가지고 있습니다.\n$FROM|Y$ 개장의 비용은 $COST|2Y$ £navprod_cost이므로, $PERTIMEPERIOD$만큼 개장할 수 있습니다.\n"
 PRODUCTION_UNITS_PER_DAY: "매일 $UNITS|Y$개"
 PRODUCTION_UNITS_PER_WEEK: "매주 $UNITS|Y$개"
 PRODUCTION_UNITS_PER_MONTH: "매월 $UNITS|Y$개"
 PRODUCTION_UNITS_PER_YEAR: "매년 $UNITS|Y$개"
 PRODUCTION_FACTORY_ASSIGN_DESC: "이 생산 라인에 £factory_item $FACTORIES|Y$ §Y군수공장§!을 할당하려면 클릭하십시오. 이를 통해 매일 £production_cost $OUTPUT|Y$의 기본 생산량을 얻게 됩니다.\n총 생산력은 §Y자원§!, §Y생산 효율§!, 그리고 다른 §Y생산량 변동치§!에 영향을 받습니다."
 PRODUCTION_DOCKYARD_ASSIGN_DESC: "이 생산 라인에 £naval_factory_icon $FACTORIES|Y$ §Y해군 조선소§!를 할당하려면 클릭하십시오. 이를 통해 매일 £navprod_cost $OUTPUT|Y$의 기본 생산량을 얻게 됩니다.\n총 생산력은 §Y자원§!과 다른 §Y생산량 변동치§!에 영향을 받습니다."
 PRODUCTION_BASE_OUTPUT: "기본 생산량: $VALUE|Y$ x $MUL|Y$"
 PRODUCTION_EFF_GAIN_HINT: "§Y효율 획득 속도 변동치:§!"
 CARRIER_AIR_WING_COMPOSITION_TITLE: "이 항공모함의 기본 비행단 편성을 설정합니다"
 MISSILE_LAUNCHER_COMPOSITION_TITLE: "이 미사일 발사대의 기본 로켓 편성을 설정합니다"
 CARRIER_AIR_WING_LIMIT_UNDER: "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH: "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER: "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC: "비행기/항공모함 수용량"
 ROCKET_WING_LIMITS_DESC: "로켓 수용량"
 ROCKET_WING_LIMIT_DESC_UNDER: "§Y이 미사일 발사대의 수용량이 완전히 활용되지 않을 것입니다§!"
 ROCKET_WING_LIMIT_DESC_OVER: "§R이 미사일 발사대의 수용량이 초과되어 모든 로켓을 탑재할 수 없을 것입니다§!"
 CARRIER_AIR_WING_LIMIT_DESC_UNDER: "§Y이 항공모함의 수용량이 완전히 활용되지 않을 것입니다§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER: "§R이 항공모함의 수용량이 초과되었으며, 이로 인해 배치된 비행단이 불이익을 받게 됩니다§!"
 CARRIER_AIR_WING_INCREASE: "수량 증가\n§GCtrl + 클릭으로 절반 증가§! \n§GShift + 클릭으로 최대치까지 증가§!"
 CARRIER_AIR_WING_DECREASE: "수량 감소\n§GCtrl + 클릭으로 절반 감소§!\n§GShift + 클릭으로 모두 제거§!"
 PRODUCTION_ENTRY_NEW: "(신형)"
 PRODUCTION_ENTRY_OUTDATED: "(구형)"
 PRODUCTION_LINE_CHANGE: "§G생산 장비를 §H변경§!하려면 클릭하십시오.\n동일한 장비의 개량형 장비로 변경할 경우, 기존 생산 효율의 일부를 유지하게 됩니다.\n§!§R이 생산 라인의 진행도를 전부 잃게 됩니다.§!"
 PRODUCTION_LINE_CHANGE_NAVAL: "§G생산 장비를 §H변경§!하려면 클릭하십시오.\n§!§R이 생산 라인의 진행도를 전부 잃게 됩니다.§!"
 PRODUCTION_EQUIPMENT_FILTER: "보병 및 포병 장비"
 PRODUCTION_ARMOR_FILTER: "기갑 차량"
 PRODUCTION_AIR_FILTER: "항공기"
 PRODUCTION_CAPITAL_SHIPS_FILTER: "주력함"
 PRODUCTION_SCREEN_SHIPS_FILTER: "보조함"
 PRODUCTION_OTHER_SHIPS_FILTER: "기타 함선"
 PRODUCTION_LACKING_RESOURCES_FILTER: "충족된 자원"
 PRODUCTION_STOCKPILING_FILTER: "비축"
 PRODUCTION_REINFORCING_FILTER: "증원"
 PRODUCTION_UPGRADING_FILTER: "개선"
 PRODUCTION_OUTDATED_FILTER: "최신 장비"
 PRODUCTION_REFITTING_FILTER: "개장"
 PRODUCTION_FILTER_CLICK_TO_HIDE: "이 유형을 모두 §R숨기려면§! §G클릭§!하십시오."
 PRODUCTION_FILTER_CLICK_TO_SHOW: "이 유형을 모두 §G보려면§! §G클릭§!하십시오."
 PRODUCTION_FILTER_SHIFTCLICK: "\n다른 모든 항목을 §R숨기려면§! §GShift+클릭§!하십시오."
 PRODUCTION_FILTER_SHIFTCLICK_AGAIN: "\n다시 모든 항목을 §G보려면§! §GShift+클릭§!하십시오."
 PRODUCTION_FILTER_RIGHTCLICK: "\n이 카테고리 전체를 펼치거나 접으려면 §G우클릭§!하십시오."
 PRODUCTION_FILTER_ARMS_FACTORIES: "사용 중인 군수공장"
 PRODUCTION_FILTER_DOCKYARDS: "사용 중인 해군 조선소"
 INTEL_CIVILIAN_FACTORIES_USED_ON_TRADE: "무역에 쓰일 것으로 예상되는 민간공장 수"
 INTEL_ARMS_FACTORIES_USED_ON_EQUIPMENT: "군사 장비 생산에 쓰일 것으로 예상되는 군수공장 수"
 INTEL_ARMS_FACTORIES_USED_ON_ARMOR: "기갑 차량 생산에 쓰일 것으로 예상되는 군수공장 수"
 INTEL_ARMS_FACTORIES_USED_ON_AIR: "항공기 생산에 쓰일 것으로 예상되는 군수공장 수"
 INTEL_DOCKYARDS_USED_ON_CAPITAL: "주력함 생산에 쓰일 것으로 예상되는 해군 조선소 수"
 INTEL_DOCKYARDS_USED_ON_SCREEN: "보조함 생산에 쓰일 것으로 예상되는 해군 조선소 수"
 INTEL_DOCKYARDS_USED_ON_OTHER: "기타 함선 생산에 쓰일 것으로 예상되는 해군 조선소 수"
 PRODUCTION_DRAG_N_DROP: "§G드래그 앤 드롭§!으로 §Y우선순위§!를 변경할 수 있습니다."
 PRODUCTION_COLLAPSE: "§G클릭§!하여 접기.\n§GCtrl + 클릭§!하여 이 카테고리 모두 접기.\n§GShift + 클릭§!하여 모든 생산 라인 접기."
 PRODUCTION_EXPAND: "§G클릭§!하여 펼치기.\n§GCtrl + 클릭§!하여 이 카테고리 모두 펼치기.\n§GShift + 클릭§!하여 모든 생산 라인 펼치기."
 PRODUCTION_FACTORY_SCALE_UP: "§G클릭§!하여 §Y$SCALE$x§!로 화면 크기를 키웁니다."
 PRODUCTION_FACTORY_SCALE_DOWN: "§G클릭§!하여 §Y1x§!로 화면 크기를 줄입니다."
 PRODUCTION_ADD_FACTORIES_CLICK: "§G클릭§!하여 §Y+1§! 증가\n§GCtrl + 클릭§!하여 §Y+5§! 증가\n§GShift + 클릭§!하여 §Y+10§! 증가"
 PRODUCTION_SUB_FACTORIES_CLICK: "§G클릭§!하여 §Y1§! 감소\n§GCtrl + 클릭§!하여 §Y5§! 감소\n§GShift + 클릭§!하여 §Y10§! 감소"
 PRODUCTION_ADD_1: "§G클릭§!하여 §Y+1§! 추가"
 PRODUCTION_ADD_5: "§GCtrl+클릭§!하여 §Y+5§! 추가"
 PRODUCTION_ADD_10: "§GShift+클릭§!하여 §Y+10§! 추가"
 PRODUCTION_SUB_1: "§G클릭§!하여 §Y1§! 감소"
 PRODUCTION_SUB_5: "§GCtrl + 클릭§!하여 §Y5§! 감소"
 PRODUCTION_SUB_10: "§GShift + 클릭§!하여 §Y10§! 감소"
 PRODUCTION_ADD_NAVAL_FACTORIES_CLICK: "§G클릭§!하여 §Y+1§! 추가"
 PRODUCTION_SUB_NAVAL_FACTORIES_CLICK: "§G클릭§!하여 §Y1§! 감소"
 PRODUCTION_CLICK_TO_APPEND_OR_INSERT: "신규 생산 라인을 마지막에 추가하려면 §G클릭§!하십시오.\n신규 생산 라인을 맨 위에 추가하려면 §GShift+클릭§!하십시오."
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME: "$STATE$ ($LVL|Y$)"
 PRODUCTION_LINE_CONVERT_NO_EQUIPMENT_IN_STOCK: "§R현재 비축량에는 $VARIANT|H$(으)로 전환하는 데 사용할 수 있는 장비가 없습니다.§!"
 PRODUCTION_LINE_CONVERT_HEADER: "비축량으로부터 전환"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION: "전환 순서:"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY: "$NUM|Y0$개의 $VARIANT|G$ (§H$TYPE$§!) 비용:"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY_NO_TYPE: "$NUM|Y0$개의 $VARIANT|G$ 비용:"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY: "$NUM|Y0$개의 $VARIANT|G$ (§H$TYPE$§!)"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY_NO_TYPE: "$NUM|Y0$개의 $VARIANT|G$"
 PRODUCTION_LINE_CONVERT_RESOURCE_COST_ENTRY: "§H$NUM$§!£resources_strip|$FRAME$"
 PRODUCTION_LINE_CONVERT_DESC: "비축량으로부터 전환하게 되면, 비축량 중 §H구형 장비§! 또는 §H노획한 장비§!를 현재 생산 라인에서 요청하는 개조 차량으로 전환하며, 이때 생산 비용이 절감됩니다. 이 작업은 비축량이 소진될 때까지 지속됩니다."
 PRODUCTION_LINE_CONVERT_SPEED_TOTAL: "전환 속도: §G+§!$SPD|G%0$"
 PRODUCTION_LINE_CONVERT_SPEED_BASE: "기본: $VAL|=+%0$"
 PRODUCTION_LINE_CONVERT_RES_NEED: "$NAME|Y$ 전환에 필요한 자원:"
 PRODUCTION_LINE_CONVERT_RES_NEED_ENTRY: "\n   £resources_strip|$FRAME$: ($NEW|Y0$ - $OLD|G0$) = $SUM|R0$"
 PRODUCTION_LINE_SHIP_NAME_ALLOCATE: "아직 다른 어떤 함선에도 붙여지지 않은 이름입니다. 추가 버튼을 §G클릭§!해서 이 이름을 생산 대기열에 등록할 수 있습니다."
 PRODUCTION_LINE_RAILWAY_GUN_NAME_ALLOCATE: "아직 다른 어떤 열차포에도 붙여지지 않은 이름입니다. 추가 버튼을 §G클릭§!해서 이 이름을 생산 대기열에 등록할 수 있습니다."
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE: "면허 생산: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL: "§H면허 생산 공장 생산량§!\n총합: $VALUE|+%$\n세부 내역:"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION: "§Y면허 생산 기술 격차§!:\n 기본: $BASE|+%$\n 변화치 총합: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER: "§Y면허 생산 변화치§!:\n 기본: $BASE|+%$\n 변화치 총합: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION: "§Y면허 보유국과 같은 세력이 아닙니다§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE: "§Y활성화된 면허 없음§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_UPGRADE_XP_COST_MODIFIER: "면허 장비: $VAL$"
 LICENSED_PURCHASE_CIC_COST: "§Y면허 생산 비용§!: £civ_factory $AMOUNT|Y$"
 PRODUCTION_NAVAL_REPAIRS_LABEL: "수리 대기열"
 PRODUCTION_NAVAL_NAME_LIST: "함선 이름"
 PRODUCTION_RAILWAY_GUN_NAME_LIST: "열차포 이름"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_FALLBACK: "함선 이름"
 PRODUCTION_RAILWAY_GUN_NAME_LIST_BUTTON_FALLBACK: "열차포 이름"
 PRODUCTION_NAVAL_NAME_LIST_EMPTY_NOT_ALLOWED: "§R이름 칸을 비워둘 수 없습니다.§!"
 PRODUCTION_NAVAL_NAME_LIST_TOO_FEW_PRODUCED: "§R이름의 수가 생산 대기열에 있는 선박 수를 초과하게 됩니다.§!"
 PRODUCTION_NAVAL_NAME_LIST_REMOVE: "§G클릭§!하여 §H이름 제거§!"
 PRODUCTION_NAVAL_NAME_LIST_NAME_RESERVED: "$NAME|H$(은)는 사용 중입니다."
 PRODUCTION_NAVAL_NAME_LIST_ADD_NAME: "§G클릭§!하여 이 라인의 다음 $EQUIPMENT|H$(을)를 $NAME|H$(이)라 명명."
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_NAME: "이 라인에서 생산되는 다음 $EQUIPMENT|H$(을)를 $NAME|H$(이)라 명명할 것입니다."
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_CLICK: "§G클릭§!하여 이름 변경."
 PRODUCTION_SHIP_REFIT_TOTAL_COSTS: "§H함선 $COUNT|T$척의 총비용:§!\n"
 PRODUCTION_SHIP_REFIT_BASE_ICCOST: "선체: $ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_BUILD_ICCOST: "신형 모듈: $ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_CONVERT_ICCOST: "개장 모듈: $ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_DISMANTLE_ICCOST: "해체된 모듈: $ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_QUICKEST_TIME: "§H조선소§!를 최대한 할당한다면, 완성까지 최대 $DAYS|H$일이 소요될 것입니다."
 PRODUCTION_SHIP_REFIT_TOOLTIP_DIFF_HEADER: "§H개장 효과§!"
 PRODUCTION_SHIP_REFIT_TOOLTIP_FROM_VARIANT_HEADER: "$VARIANT$(으)로부터 ($SHIP_COUNT|H$개 선택됨)"
 PRODUCTION_SHIP_REFIT_TOOLTIP_NO_STAT_CHANGES: "성능 변화 없음"
 PRODUCTION_SHIP_REFIT_TOOLTIP_MORE_VARIANTS: "다른 파생형 장비 ($SHIP_COUNT|H$개 선택됨)"
 PRODUCTION_TANK_REFIT_BASE_ICCOST: "차체: $ICCOST|H2$"
 PRODUCTION_TANK_REFIT_QUICKEST_TIME: "§H생산 효율 한도§!가 최대치일 때, 할당된 각 공장은 $NUM_UNITS_PER_TIME_PERIOD$(을)를 변환합니다"
 PRODUCTION_SUB_UNIT_FILTER: "$SUBUNIT|H$만 표시 ($COUNT|H$개 일치)"
 PRODUCTION_EQUIPMENT_ROLE_NO_FILTER: "모든 역할 보기"
 PRODUCTION_EQUIPMENT_ROLE_FILTER: "$ROLE|H$ 역할의 장비만 보기"
 PRODUCTION_COST_MODIFIERS: "§Y£production_cost£생산 비용 변동치:§!"
 PRODUCTION_COST_MODIFIER_ITEM: "$REASON$: $VALUE|-%$"
 BONUS_PRODUCTION_COST_FACTOR: "생산량 비용"
 BONUS_PRODUCTION_CAPACITY_FACTOR: "생산량"
 BONUS_PRODUCTION_EFFICIENCY_CAP_FACTOR: "생산 효율 한도"
 BONUS_PRODUCTION_EFFICIENCY_GAIN_FACTOR: "생산 효율 획득"
 BONUS_PRODUCTION_RESOURCE_NEED_FACTOR: "생산 자원 필요"
 BONUS_PRODUCTION_RESOURCE_PENALTY_FACTOR: "생산 자원 불이익"
 BONUS_PRODUCTION_CONVERSION_SPEED_FACTOR: "생산 전환 속도"
